### ISSUE TITLE
Could you provide the training code ?

### ISSUE THREAD

**Issue by gitUserGoodLeaner** [tonghe90/textspotter#1]
@tonghe90  Hello！  Could you provide the training code?  Current project only support testing...

**Comment by tonghe90** [comment]
@gitUserGoodLeaner Hi, sorry, for some ip issue, we cannot release the training code. Please refer to our paper for more details. If you have any question please feel free to ask

**Comment by gitUserGoodLeaner** [comment]
@tonghe90 Thanks very much !
