### ISSUE TITLE
Out of memory error on test example

### ISSUE THREAD

**Issue by weinman** [tonghe90/textspotter#10]
When I try to run the simple example given in the README

    python test.py --img=./imgs/img_105.jpg

I get an out of memory error: 

    F0426 09:41:13.545714 20964 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
    *** Check failure stack trace: ***

I am trying to run this on a GTX 1080, which has 8120 MB of global memory (according to `deviceQuery`). 

When I tabulate the "Memory required for data" lines from the caffe log output, it adds up to 381 GB, though perhaps this isn't all required simultaneously or it is otherwise a double-counting. The same failure occurs when I try a much smaller (140x180 px) crop of the same image.

Is that right? Do you expect the model to fit and run within roughly 8GB of GPU memory? If not, how much memory is required to run this model?

**EDIT**: Same error happens on another host with K40 and K80 GPUs (each with roughly 12GB of GPU memory)

**Comment by tonghe90** [comment]
@weinman  Hi, did you check you have released the memory before you run this code? It's ok for me to run the demo on 1080ti.

**Comment by weinman** [comment]
I'm not sure what you mean exactly by "released the memory". `nvidia-smi` shows no GPU activity:


    $ nvidia-smi 
    Thu Apr 26 20:11:43 2018       
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  Tesla K80           Off  | 00000000:04:00.0 Off |                    0 |
    | N/A   42C    P0    61W / 149W |      0MiB / 11441MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
    |   1  Tesla K80           Off  | 00000000:05:00.0 Off |                    0 |
    | N/A   34C    P0    73W / 149W |      0MiB / 11441MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
    |   2  Tesla K40c          Off  | 00000000:06:00.0 Off |                    0 |
    | 23%   37C    P0    66W / 235W |      0MiB / 11441MiB |     96%      Default |
    +-------------------------------+----------------------+----------------------+
                                                                                   
    +-----------------------------------------------------------------------------+
    | Processes:                                                       GPU Memory |
    |  GPU       PID   Type   Process name                             Usage      |
    |=============================================================================|
    |  No running processes found                                                 |
    +-----------------------------------------------------------------------------+
    $ python test.py --img=./imgs/img_105.jpg
    Called with args:
    Namespace(img='./imgs/img_105.jpg', nms=0.2, prototxt_iou='./models/test_iou.pt',     prototxt_lstm='./models/test_lstm.pt', save_dir='./results', scales='2240, 1920, 1792, 2080', thresholds='0.95, 0.95, 0.95, 0.95', weight='./models/textspotter.caffemodel')
    ./models/textspotter.caffemodel
    ...
    I0426 20:13:22.515193 12246 net.cpp:744] Ignoring source layer reg_loss
    1 / 1:  ./imgs/img_105.jpg
    F0426 20:13:23.756857 12246 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
    *** Check failure stack trace: ***
    Aborted (core dumped)
    $ 

Is there something different I should be doing? A simpler Caffe-based test I should run?

**Comment by LQNew** [comment]
Hey,I have met the same problem, I have a GTX TitanX, which has 12G memory , but I can't run the test.py, I wish author release the nice solutions. Also, if you solved it, please tell me!

**Comment by LQNew** [comment]
1 / 500:  img_161.jpg
0.506461828947 uiee
0.910335918268 dee
0.82194237411 koue
0.873585417867 geox
0.613331668079 lote
0.801094040275 peox
0.868016913533 xoue
0.914753034711 peox
2 / 500:  img_41.jpg
0.929699702696 creatiuityi
0.999763659069 masking
0.942161212365 marker
0.94941151684 creatiuityl
0.999508193561 masking
0.929480910301 marker
0.999231517315 tape
0.895427898927 creatiuityl
0.981489649841 masking
0.918323706497 creatiuityi
0.999186924526 masking
0.999004155397 tape
0.984221329292 market
3 / 500:  img_376.jpg
0.975755376475 eastern
0.999636697769 watch
0.760963380337 gous
0.614728137851 so
0.991404993193 pastern
0.930275213718 waich
0.663194783032 600u
0.99942029374 eastern
0.99492739439 watch
0.700679838657 6004
0.325231991708 38
0.992786177567 eastern
0.998411095142 watch
0.590321339667 gout
4 / 500:  img_15.jpg
F0427 11:17:20.844681 29944 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)

Well, I just magically ran a piece of code(but I didn't know what happend!!)However, when I use ICDAR2015 to test, this code can only run for just small amount of images...This is a metaphysics! I hope somebody help me !!

**Comment by tonghe90** [comment]
@LQNew You can change the test size of the image, but from my experience, if you want to run over the ICDAR15 dataset, 12G memory should be enough.

**Comment by tonghe90** [comment]
@LQNew Or, you can remove the largest size to check if it is can run through the dataset

**Comment by weinman** [comment]
@tonghe90 when I try to run a very small (140x180 px) image through the code, I still get the out of memory error.

I'm using CUDA 9.1 with patches 1,2 and 3; I had to compile the textspotter version of Caffe without cuDNN because using my host's version of CUDNN 7.1 gave compile errors.

**Comment by LQNew** [comment]
@tonghe90  thx for your suggestion, now I truly doubt that I run test.py incorrectly! Because when I test images, the more images I test, the faster memory grows, just after I test several images, the memory will not support the next running...

**Comment by LQNew** [comment]
@tonghe90  I just modify a small part of the code:

parser.add_argument(
        '--img',
        dest='img',
        #default='./imgs/img_105.jpg',
        default='./data/test',
        help='img file or folder',
        type=str
    )

and here:

    for ind, image_name in enumerate(imgs_files):
        new_boxes = list()
        words = list()
        words_score = list()
        image_id = image_name.split('/')[-1].split('.')[0]
        print '%d / %d: ' % (ind+1, len(imgs_files)), image_name
        im = cv2.imread(args.img+'/'+image_name) #get the img path
        h, w, c = im.shape

Can you tell me why ?

**Comment by tonghe90** [comment]
@weinman I think it's the cudnn problem. I use cuda8.0 and cudnn 6.0

**Comment by weinman** [comment]
Thank you, I tried again with CUDA 8.0 and cuDNN 7.1.2 and it seemed to work. I did get the same compiler warnings as the 9.1/7.1.2 pairings when compiling caffe. (I don't get these warnings when compiling from the most recent caffe master.) 

    In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                     from ./include/caffe/common.hpp:19,
                     from ./include/caffe/blob.hpp:8,
                     from ./include/caffe/caffe.hpp:7,
                     from python/caffe/_caffe.cpp:17:
    ./include/caffe/util/cudnn.hpp: In function ‘const char* cudnnGetErrorString(cudnnStatus_t)’:
    ./include/caffe/util/cudnn.hpp:21:10: warning: enumeration value ‘CUDNN_STATUS_RUNTIME_IN_PROGRESS’ not handled in switch [-Wswitch]
       switch (status) {
              ^

I reverted back to 9.1/7.1.2, ignored the warnings, and the demo runs successfully. 

Another suggestion for the README: cuDNN required!

**Comment by weinman** [comment]
@tonghe90 Another update: I cannot get any other image to run without the memory failure, even a 180x140 crop (around the sign) of the otherwise successful example image.

The last log message before the failure is as follows:

    I0428 09:20:00.200690  5994 net.cpp:744] Ignoring source layer reg_loss
    1 / 1:  ./imgs/img_105c2.jpg

Fully reverting back to 8.0/6.0 as you pointed out, eliminates all the compiler warnings during the caffe build, but still causes the same memory failure.

Any other ideas?

**Comment by LQNew** [comment]
@weinman  Thx for your suggestion, I open cuDnn in Makefile.config, and magically, the code can run! I computer the memory, it requests about 12G memory to run through ICDAR15~

**Comment by weinman** [comment]
Perhaps a final update on this question. 

I had not realized the default values of the `test.py` parameter `--scales-ms` seem to be tuned to the one example image. Thus, when I provided a smaller (more square) image without specifying/overriding the image scale, the script resized my input image to be much larger, which ended up exceeding GPU capacity. 

Setting the scales parameter appropriately allowed the image to go through just fine.

@tonghe90 Is there a range of raw pixel heights of text for which the detector/recognizer works best? If so, it might be helpful to add a note in the README indicating this so that users can set `--scales-ms` appropriately for their data.

**Comment by tonghe90** [comment]
@weinman This script is used for icdar15, which have unified size. I didnot test it for other situations. I will add the note after testing.

**Comment by AndresPMD** [comment]
Hello @weinman  !
It seems to me that you make this code work. Did you have any issues when installing this custom version of caffe at the moment of running make test with these two files:
test_bn_layer.cpp  test_deformconv_layer.cpp

**Comment by weinman** [comment]
I never got the unit tests to run; as you pointed out, I presume its because there is no test file for the custom layer. Other than that, `make all pycaffe` should get the code running as intended.

**Comment by AndresPMD** [comment]
@weinman Thanks for your advice. As you said, some images work correctly and some smaller images exceed my GPU size (12 GB). What was the scale of the nms that you use to make them fit?
Thanks in advance.

**Comment by weinman** [comment]
@DreadPiratePsyopus I've found that if I keep the image size to 512x512 my examples (not ICDAR15) work. Sometimes a 1024x1024 image will exceed memory; I'm not sure (yet) which stage of the pipeline is exhausting memory,.

**Comment by AndresPMD** [comment]
@weinman, I changed the multi scales to 7/8 of the original one. 
to
default = '1960, 1680, 1568, 1820'

I havent experienced any error since, nonetheless probably  this model is not fined tuned for this scales. Probably you can use those scales depending on your application of this model.

**Comment by prajwalkr** [comment]
In my case, I get out of memory errors even by using just 360, 720 scales but when there is a lot of text (15 - 20) words in the image. My GPU memory is 12GB.
