### ISSUE TITLE
Only the last scale is saved among scaled input results

### ISSUE THREAD

**Issue by bado-lee** [tonghe90/textspotter#11]
Hi, in your test.py,
https://github.com/tonghe90/textspotter/blob/e904571b529bf0d59f87164343567db3a12c5135/test.py#L241
it seems,
```
new_boxes, words, words_score
```
are being refreshed during the loop and only the result for scale 2080 seems to be processed afterwards.
Looks like it needs merging process of each result otherwise seems redundant.
Would you please explain if I'm missing something?

**Comment by tonghe90** [comment]
Hi @bado-lee , thanks for reminding, bug fixed

**Comment by bado-lee** [comment]
@tonghe90 Thank you for prompt reply :)
