### ISSUE TITLE
Error loading parameters

### ISSUE THREAD

**Issue by AndresPMD** [tonghe90/textspotter#12]
Hello @tonghe90,

Congrats for the good project and paper. I am trying to test you code but I am having problems loading the params, do you have any idea why is this happening?

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0514 12:58:54.210842  2459 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0514 12:58:54.210868  2459 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0514 12:58:54.210873  2459 _caffe.cpp:142] Net('./models/test_iou.pt', 1, weights='./models/textspotter.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 7067:24: Message type "caffe.LayerParameter" has no field named "point_bilinear_param".
F0514 12:58:54.243449  2459 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./models/test_iou.pt

**Comment by tonghe90** [comment]
Hi @DreadPiratePsyopus are you using our caffe or your own?

**Comment by AndresPMD** [comment]
Hi @tonghe90, no it is the original BVLC version. Do you think that the test.py can be executed on a cpu caffe version as well?

**Comment by tonghe90** [comment]
@DreadPiratePsyopus You can try our caffe version, as I write some other layer designed for this task. you can check it according to [this](https://github.com/tonghe90/textspotter/blob/master/caffe/src/caffe/proto/caffe.proto).

**Comment by tonghe90** [comment]
@DreadPiratePsyopus This code can run on CPU, all the layer has cpu version.

**Comment by AndresPMD** [comment]
Thank you @tonghe90, currently I am trying to install your caffe version. 
The make all command worked, but when I execute make test I encounter the following error:

src/caffe/test/test_bn_layer.cpp:7:37: fatal error: caffe/layers/bn_layer.hpp: No such file or directory
compilation terminated.
Makefile:581: recipe for target '.build_release/src/caffe/test/test_bn_layer.o' failed
make: *** [.build_release/src/caffe/test/test_bn_layer.o] Error 1

Any reason why is this happening?

Thanks in advance.

**Comment by AndresPMD** [comment]
@tonghe90 
Btw on the original caffe, the test_bn_layer.cpp is not included. Should it be tested? Let me know any idea. Thank you!

**Comment by AndresPMD** [comment]
Btw @tonghe90 
The problem arises when compiling your custom version of caffe with the files:
test_bn_layer.cpp  -> when calling file "caffe/layers/bn_layer.hpp"
test_deformconv_layer.cpp -- > when calling file "caffe/layers/deform_conv_layer.hpp"

Do you know about how to solve this errors?!

**Comment by tonghe90** [comment]
@DreadPiratePsyopus , You can ignore the test process.

**Comment by AndresPMD** [comment]
@tonghe90 Yes, so I did and it worked...I am debugging some other issues. Thank you.
