### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by zhuliqian** [tonghe90/textspotter#15]
models/textspotter.caffemodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0718 15:41:54.913141 23734 _caffe.cpp:140] DEPRECATION WARNING - deprecated use of Python interface
W0718 15:41:54.913169 23734 _caffe.cpp:141] Use this instead (with the named "weights" parameter):
W0718 15:41:54.913173 23734 _caffe.cpp:143] Net('models/test_iou.pt', 1, weights='models/textspotter.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 7067:24: Message type "caffe.LayerParameter" has no field named "point_bilinear_param".
F0718 15:41:54.915925 23734 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/test_iou.pt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by tonghe90** [comment]
Can you describe more specific? How can I reimplement the error?

**Comment by zhuliqian** [comment]
when I run python test.py --img=imgs/img_105.jpg
An error occurred
Called with args:
Namespace(img='imgs/img_105.jpg', nms=0.2, prototxt_iou='models/test_iou.pt', prototxt_lstm='models/test_lstm.pt', save_dir='results', scales='2240, 1920, 1792, 2080', thresholds='0.95, 0.95, 0.95, 0.95', weight='models/textspotter.caffemodel')
models/textspotter.caffemodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0718 15:41:54.913141 23734 _caffe.cpp:140] DEPRECATION WARNING - deprecated use of Python interface
W0718 15:41:54.913169 23734 _caffe.cpp:141] Use this instead (with the named "weights" parameter):
W0718 15:41:54.913173 23734 _caffe.cpp:143] Net('models/test_iou.pt', 1, weights='models/textspotter.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 7067:24: Message type "caffe.LayerParameter" has no field named "point_bilinear_param".
F0718 15:41:54.915925 23734 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/test_iou.pt
*** Check failure stack trace: ***
Aborted (core dumped)
caffe,pycaffe都make了，由于之前有一个错，所以在test.py里改了这里
old_path = os.getcwd()
os.chdir(caffe_root + "/python")
import caffe
os.chdir(old_path)

用的python2.7 cuda8 cudnn6

**Comment by yeLer** [comment]
![image](https://user-images.githubusercontent.com/16631986/42877476-5cd9b574-8abc-11e8-91aa-2f677f6a8503.png)
I have the problem which is same as you.have you solved it?

**Comment by zhuliqian** [comment]
沒有

**Comment by tonghe90** [comment]
Hi @zhuliqian @yeLer , can you rebuild caffe. Make sure 'make clean' before remake it.

**Comment by zhuliqian** [comment]
好了，非常感謝！

**Comment by tonghe90** [comment]
@zhuliqian @yeLer I will close this and add it to the READ.ME

**Comment by yeLer** [comment]
I have solved the problem.First I used the caffe version which is Original ecology，but some layers in this project had been modified by author.so I need to used the caffe which comes from this project.Second when I compile this caffe,I meet a new problem( make: *** [.build_release/src/caffe/layers/at_layer.o] Error 1).Fortunately，this link #9 help me a lot.Now I could run it normally.Thank you very much!
![image](https://user-images.githubusercontent.com/16631986/42930543-dbfd0a0a-8b6f-11e8-948a-4f1c76f119f7.png)
