### ISSUE TITLE
out of memory exception

### ISSUE THREAD

**Issue by fortuneko** [tonghe90/textspotter#17]
Hi ,i run the test.py with a new image, it comes up with an exception with memory, messages as below:
```
1 / 1:  /home/eng_imgs/web.jpeg
F0724 12:09:38.190629 40484 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
```

The memory size of my gpu is 11178MiB, how should i tune the code to run on my gpu server?

**Comment by weinman** [comment]
see #10

**Comment by fortuneko** [comment]
thanks weinman,
