### ISSUE TITLE
'Python' layer unregistered in models/test_iou.pt

### ISSUE THREAD

**Issue by VanillaChelle** [tonghe90/textspotter#2]
Hi there,

Sorry to bother but I've encountered an issue while running the test code.
<del>The message popped up that `F0329 ... layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python`.
May you please check up is there any problem with the `.pt` file?</del>

Thanks and have a nice day : )

**Comment by tonghe90** [comment]
@VanillaChelle Hi, did  you check that WITH_PYTHON_LAYER:= 1 when you  compile caffe

**Comment by VanillaChelle** [comment]
Sorry again for raising this issue, just found that I've accidentally deleted the `WITH_PYTHON_LAYER` line from the Makefile.
I'll close this issue.
Thanks for your code!
