### ISSUE TITLE
strong, weak and generic lexicon

### ISSUE THREAD

**Issue by yyangmei** [tonghe90/textspotter#21]
您好，我不太理解强、弱和通用字典的定义以及使用，请问强、弱和通用字典是什么意思？怎么用他们来识别？为什么识别结果会有差异？

Hello, I don't quite understand the definition and use of strong, weak and general lexicon. What are strong, weak and general lexicon? How to use them to identify? Why are there differences in recognition results in terms of using a strong, weak and generic lexicon? I need your help very much,looking forward to your answer!Thank you so much!

**Comment by tonghe90** [comment]
@yyangmei Strong, weak and general means the size of the dictionary. Strong dict may have 50 lexicons and generic dict contains about 90k lexicons. You can compare your results with the work in the dictionary and correct your results
