### ISSUE TITLE
Do i need to write OHEM layer

### ISSUE THREAD

**Issue by fsluckymao** [tonghe90/textspotter#26]
Hi @tonghe90 ：
i was tried to implement your code recently, and found a layer named "OHEM",i am not sure whether i need to write this layer or not.

**Comment by fsluckymao** [comment]
another question:
 in Class det_nms_layer 
what is the point of this line,add a coloum which is all zero to orient_bboxes, This doesnt  seem to work           
https://github.com/tonghe90/textspotter/blob/0166abdbe68bfe0a416a4a1d35ab8d1e1fcfe262/pylayer/tool_layers.py#L253

**Comment by tonghe90** [comment]
@fsluckymao Thanks for your interest. OHEM is used for online hard example mining. It can increase the performance for detection, but mot obviously.

**Comment by tonghe90** [comment]
@fsluckymao The first column is the box id in the batch size. As is presented in our comment, the first dimension is 1, which means just one image .

**Comment by fsluckymao** [comment]
thank you for your answer @tonghe90 , here is another question confuse me:
in train.pt ,"gt_bbox" is noted by ” N * 8 ### grounding truth boxes for text (for computing loss)”
but in Class gen_gts_layer which in tool_layers.py it is noted by "bottom[0]: gt_label [N,1,sz,sz]"
https://github.com/tonghe90/textspotter/blob/0166abdbe68bfe0a416a4a1d35ab8d1e1fcfe262/models/train.pt#L7
https://github.com/tonghe90/textspotter/blob/0166abdbe68bfe0a416a4a1d35ab8d1e1fcfe262/models/train.pt#L6885
https://github.com/tonghe90/textspotter/blob/0166abdbe68bfe0a416a4a1d35ab8d1e1fcfe262/pylayer/tool_layers.py#L268

**Comment by fsluckymao** [comment]
Hi @tonghe90 :
I have done my training,but my model perform a bad result, could release your solver.prototxt as my guide

**Comment by tonghe90** [comment]
@fsluckymao  I will try to release next week

**Comment by Tangjunjun0925** [comment]
@fsluckymao @tonghe90 :
same confusion about the  shape mismatch bewteen "gt_bbox" which is noted in train.pt and "gt_label" which is noted in pylayer/tool_layers.gen_gts_layer.

**Comment by tonghe90** [comment]
base_lr: 0.001
test_interval: 2000
test_iter: 200
#lr_policy: "plateau"
lr_policy: "multistep"
gamma: 0.1
#plateau_winsize: 40000
#plateau_winsize: 80000
#plateau_winsize: 100000
#plateau_winsize: 120000
stepvalue: 20000
stepvalue: 50000
stepvalue: 100000
#stepvalue: 10000
#stepvalue: 20000

clip_gradients: 10

momentum: 0.9
weight_decay: 0.0002
display: 20
average_loss: 100
max_iter: 200000
snapshot: 2000
iter_size: 4
type: "Adam"

**Comment by fsluckymao** [comment]
@tonghe90 thank you for your guidance. i will close this issue.
