### ISSUE TITLE
how about the time cost? 

### ISSUE THREAD

**Issue by wyhgood** [tonghe90/textspotter#29]
I run test.py on Tesla P40,   if I set the scale to 1000,  the detection part needs time 1s around.
when I set the scale to 300, then the detection part time is 0.3s around.     how about others?  is it normal.  and if I want to speed the forword, is there any sugestion?  thanks

**Comment by tonghe90** [comment]
@wyhgood There are two parts you can improve, the first part is the recognition branch, we use a pretty deep branch for it. But we found out you could use shallow layers to achieve the same performance. The other way is the dictionary size. What we provide is 90k dicts. It means we have to compare the result with all the items in the dict. You can also use the direct output or a smaller dictionary

**Comment by wyhgood** [comment]
thank you for suggestion, I will try it
