### ISSUE TITLE
Therer are many errors about "at_layer.cpp" and other layers

### ISSUE THREAD

**Issue by liuxi2018** [tonghe90/textspotter#3]
Hi He:
**I git clone your code, when I make your code, we encounter many errors. Is the code you have released is incomplete or other reasons? Some of the errors are as follows：**

src/caffe/layers/at_layer.cpp:18:20: error: request for member ‘output_h’ in ‘param’, which is of non-class type ‘const int’
  output_H_ = param.output_h();
                    ^
src/caffe/layers/at_layer.cpp:20:12: error: request for member ‘has_output_w’ in ‘param’, which is of non-class type ‘const int’
  if (param.has_output_w()) {
            ^
src/caffe/layers/at_layer.cpp:21:21: error: request for member ‘output_w’ in ‘param’, which is of non-class type ‘const int’

/usr/include/c++/5/bits/stl_vector.h:303:7: note:   candidate expects 3 arguments, 5 provided
/usr/include/c++/5/bits/stl_vector.h:264:7: note: candidate: std::vector<_Tp, _Alloc>::vector(const allocator_type&) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<int>]
       vector(const allocator_type& __a) _GLIBCXX_NOEXCEPT
       ^
/usr/include/c++/5/bits/stl_vector.h:264:7: note:   candidate expects 1 argument, 5 provided
/usr/include/c++/5/bits/stl_vector.h:253:7: note: candidate: std::vector<_Tp, _Alloc>::vector() [with _Tp = int; _Alloc = std::allocator<int>]

**Comment by tonghe90** [comment]
Hi @liuxi2018 , is the Makefile.config contain CUSTOM_CXX := g++ -std=c++11?

**Comment by donglinAI** [comment]
Very useful,Thanks very much !@tonghe90

**Comment by Tsui-Xianjun** [comment]
how the question to be solved?
