### ISSUE TITLE
paramater "rf"

### ISSUE THREAD

**Issue by fsluckymao** [tonghe90/textspotter#31]
Hi tonghe:

Could you please tell what is the role of paramater 'rf' in "det_nms_layer", why "pre_bbox" need to Multiplied by it?
https://github.com/tonghe90/textspotter/blob/0166abdbe68bfe0a416a4a1d35ab8d1e1fcfe262/pylayer/tool_layers.py#L227

**Comment by tonghe90** [comment]
@fsluckymao The rf is just a scale parameter, because the ground truth is divided by this parameter
