### ISSUE TITLE
@tonghe90，我的是1070

### ISSUE THREAD

**Issue by zhangshuaitao** [tonghe90/textspotter#5]
1 / 1:  ./imgs/img_105.jpg
F0409 21:07:56.721240 21671 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***

**Comment by tonghe90** [comment]
@zhangshuaitao , you can use smaller image size, this model is designed for icdar15, which may need large input size.

**Comment by zhangshuaitao** [comment]
@tonghe90 Thank you！
