### ISSUE TITLE
Meaning of sample_gt_cont in test_iou.pt?

### ISSUE THREAD

**Issue by gitUserGoodLeaner** [tonghe90/textspotter#6]
@tonghe90 Sorry for another question to ask,  I still not clear the function of sample_gt_cont in decoder layer,  could you give an explanation?

**Comment by tonghe90** [comment]
@gitUserGoodLeaner The cont is an indicator used for lstm. Please refer to the implementation of lstm for details. [Lstm](https://github.com/tonghe90/textspotter/blob/master/caffe/src/caffe/layers/lstm_layer.cpp)

**Comment by tonghe90** [comment]
@gitUserGoodLeaner Cont is an indicator used for lstm. Please refer to the implementation of [lstm](https://github.com/tonghe90/textspotter/blob/master/caffe/src/caffe/layers/lstm_layer.cpp) for details
