### ISSUE TITLE
Will you release the training code?

### ISSUE THREAD

**Issue by smilewsw** [tonghe90/textspotter#8]

**Comment by tonghe90** [comment]
@smilewsw , Thanks for your interest in our work. For some IP issue, I don't intend to release the training code. If you have any question, please feel free to contact me.

**Comment by wanghaisheng** [comment]
@tonghe90   can you improve your existing trained model using [ctwdataset](https://ctwdataset.github.io/) and [ ICDAR2017 Robust Reading Challenge on COCO-Text](http://rrc.cvc.uab.es/?ch=5&com=downloads)  and [Overview - ICDAR2017 Competition on Multi-lingual scene text detection and script identification]()

**Comment by Jacoobr** [comment]
@tonghe90 Hello tonghe90, Thanks for your amazing work. I'm a fresh researcher  on text detection and recognition work. Now, my work is to detect and recognize the text on the logo of many shops.Your work will inspire me a lot to my task. But I'm confused with the step of training the model  with the method you mentioned with my own data set. The problems are as follows: 1) How can I use (or organize) the network structure of [test_iou.pt、test_lstm.pt](https://github.com/tonghe90/textspotter/tree/master/models) that you provided  when I training my own model which i plane fine tune with your textspotter.caffemodel that you trained. 
What's more, would you mind provide me the training network structure (train_val.pt) that you used in your paper. There is my email address:  _xiaojianli@stu.xjtu.edu.cn_. Your work will help me a lot to my research.  Look forward to your favourable reply. Thanks.

**Comment by tonghe90** [comment]
Hi @Jacoobr I will release the training.pt someday, but I am now busy other tasks. So it may be this weekend
