### ISSUE TITLE
make: *** [.build_release/src/caffe/layers/at_layer.o] Error 1

### ISSUE THREAD

**Issue by LQNew** [tonghe90/textspotter#9]
When I run make -j8, I  met this problem, I tried some solutions on Internet, but they didn't work...Can you help me solve it ?

**Comment by LQNew** [comment]
Well, I have solved this problem, just add "CXXFLAGS+=-std=c++11" this sentence to your makefile.config

**Comment by weinman** [comment]
@LQNew is not the first to encounter this (see issue #3); I'd suggest @tonghe90 add a note to the README

**Comment by tonghe90** [comment]
@LQNew @weinman I will add this to the README
